coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "moten/backend/torch_cuda.py"
  - "moten/backend/torch_mps.py"
  - "moten/viz.py"
  - "moten/io.py"
  - "moten/extras.py"
